name: Publish to Cloudflare R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build 'build' folder
        run: |
          docker compose run --rm builder

      - name: Sanity check before we accidentally nuke the bucket
        run: |
          if [ -z "$(ls -A build/)" ]; then
            echo "Build directory is empty, aborting."
            exit 1
          fi

      - name: Upload build/ to Cloudflare R2
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: build
          destination-dir: /
          keep-file-fresh: true

      - name: Sanity check before we accidentally nuke the bucket
        run: |
          if [ -z "$(ls -A build/)" ]; then
            echo "Build directory is empty, aborting."
            exit 1
          fi
