name: update hashes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  update_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Update submodules to latest remote
        run: git submodule update --init --recursive --remote

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: run update_hashes.py
        run: .github/workflows/update_hashes.py

      - name: Commit hash file
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update source file hashes via Github Actions"
          file_pattern: "hashes.txt"
