name: workspace testing playground
on:
  # Allows running from the github UI.
  workflow_dispatch:

jobs:
  playground_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        run: python3 -m pip install -r .github/workflows/requirements.txt

      - name: Run validate_metadata.py
        run: .github/workflows/validate_metadata.py
